# Generated by Django 3.1.4 on 2021-05-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podfame_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestprofile',
            old_name='background_info',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='guestprofile',
            old_name='experience',
            new_name='interests',
        ),
        migrations.RenameField(
            model_name='guestprofile',
            old_name='expertise_area',
            new_name='pod_exp',
        ),
        migrations.RenameField(
            model_name='guestprofile',
            old_name='facebook_url',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='guestprofile',
            name='occupation',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='why_user_pods',
            field=models.CharField(default=5, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
