# Generated by Django 3.1.4 on 2021-05-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podfame_main', '0002_auto_20210508_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestprofile',
            old_name='website_url',
            new_name='facebook_url',
        ),
    ]
